"""Added dual reminder columns

Revision ID: 799bff3bac8f
Revises: cdf639189663
Create Date: 2025-12-16 00:37:01.774991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799bff3bac8f'
down_revision = 'cdf639189663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date_6mo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date_1yr', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_record', schema=None) as batch_op:
        batch_op.drop_column('due_date_1yr')
        batch_op.drop_column('due_date_6mo')

    # ### end Alembic commands ###
