"""Add discount_percentage to PriceList

Revision ID: aae8cdb738aa
Revises: e0847ed090c5
Create Date: 2026-01-30 00:57:22.238906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae8cdb738aa'
down_revision = 'e0847ed090c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###
